version: '2'
services:
  db:
    container_name: koel_db
    image: mysql:5
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    network_mode: bridge

  koel:
    container_name: koel_webapp
    build: .
    links:
      - db
    ports:
      - 8123:8000
    volumes:
      - $MUSIC_FOLDER:/music
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=$VIRTUAL_PORT
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    network_mode: bridge
    labels:
      - rap.host=$VIRTUAL_HOST
      - rap.port=$VIRTUAL_PORT
      - rap.le_host=$LETSENCRYPT_HOST
      - rap.le_email=$LETSENCRYPT_EMAIL
